id: QmTpxk71xH3aLDUwsGARXqVueCdFKKCsLbM3mDKJxDhPWS
description: Endpoint to get the chat's web socket url
tags:
    - chatendpoint
    - websocketgen
trigger:
    type: http
    method: POST
    paths:
        - /chatendpoint
execution:
    timeout: 1s
    memory: 10MB
    call: chatendpoint
source: inline
domains:
    - generated
