id: QmTpxk71xH3aLDUwsGARXqVueCdFKKCsLbM3mDKJxDhPWS
description: Endpoint to get the chat's web socket url
tags:
    - chatendpoint
    - websocketgen
source: .
trigger:
    type: http
    method: POST
    paths:
        - /chatendpoint
domains:
    - generated
execution:
    timeout: 60s
    memory: 10MB
    call: chatendpoint
