id: QmPNxLqqnmjHfMe96Z3oUUVb9FUkFtsqkfsQDRYSk5HDzs
description: tauchat endpoint
tags:
    - tauchat
    - endpoint
source: .
trigger:
    type: http
    method: POST
    paths:
        - /tauchatendpoint
domains:
    - generated
execution:
    timeout: 1m
    memory: 60MB
    call: tauchatendpoint


